
name: Hello world from github actions

on:
  push:
    branches:
      - master
  # when mergeing 2 branches (dumb naming but ok)
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  # jobs are ran in parallel, while steps are ran sequentially 
  hello_world:
    # this runs on docker container within github servers?
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world!
        run: echo "Hello, world!"
  
  hello_world_job2:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world, but on a different job!
        run: sleep 3 # make it nap for a while.