name: Deploy webserver to AWS elastic beanstalk (manual) 

on:
  workflow_run:
    workflows: ["CI pipeline for python webserver (src/webserver)"]
    types: [completed] # workflow depends on another workflow

jobs:
  deploy:
    name: Deploy to elastic beanstalk
    environment: prod
      
    needs:
      - test_code
      - make_artifact
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploying to AWS EBA
        run: echo "Deploying..."
      
          