name: Deploy webserver to AWS elastic beanstalk (callable) 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to elastic beanstalk
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to aws account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create new AWS EBS Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.AWS_EBS_APP_NAME }} \
            --source-bundle S3Bucket="${{ secrets.ARTIFACT_S3_BUCKET_NAME }}",\
            S3Key="webserver-artifact-${{ github.sha }}.zip" \
            --version-label "webserver-version-${{ github.sha }}"
      
      - name: Deploy newmade application version
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.AWS_EBS_APP_NAME }}-env \
            --version-label "webserver-version-${{ github.sha }}"

